name: 'SemVer Validation Action'
description: 'Validate SemVer'
inputs:
  version:  # id of input
    description: 'Version'
    required: true
    default: '0.0.0'
outputs:
  is-valid: # id of output
    description: 'Return if the input version is valid'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'check-square'
  color: 'gray-dark'

