on: push

name: Tests the action
jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the action with success
        uses: ./
        with:
          version: '1.7.0-alpha1'
      - name: Run the action with failure
        id: failingStep
        continue-on-error: true
        uses: ./
        with:
          version: '1.A.0'
      - name: Check if previous action run has outcome 'failure'
        if: ${{ steps.failingStep.outcome != 'failure' }}
        run: exit 1